#! /bin/bash

is_root () {
    # is root

    if [ $EUID -ne 0 ]; then
        return 1
    else
        return 0
    fi
}

connect_root() {
    is_root
    if [ $? -ne 0 ]; then
        sudo su
    fi

    while true; do
     read -p "You did not connect as root, do you want to try again? (y/n) " yn
     
     case $yn in
        [yY] ) 
            connect_root
            break;;
        [nN] )
            echo "Exiting..."
            exit 1
            break;;
        * ) echo "Please answer y or n.";;
        esac
    done
}