#! /bin/sh
# This script is used to take a screenshot of the current screen using
# flameshot. It is intended to be used with the Xorg display server.

pkill flameshot
sleep 0s
flameshot &
flameshot gui -c
sleep 1s
pkill flameshot